# Generated by Django 5.1.1 on 2024-10-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('web_app', '0003_delete_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='filial',
        ),
        migrations.AddField(
            model_name='user',
            name='filial',
            field=models.ManyToManyField(to='web_app.filial'),
        ),
    ]
