# Generated by Django 5.0.3 on 2024-08-29 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.filial')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('message', models.CharField(max_length=250)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.filial')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.location')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devEui', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('ДТ', 'ДТ'), ('ДиВх', 'ДиВх'), ('485RTU', '485RTU')], max_length=250)),
                ('information', models.CharField(max_length=250)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.filial')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.location')),
            ],
        ),
        migrations.CreateModel(
            name='DiscreteVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('Дискретный вход 1', 'Дискретный вход 1'), ('Дискретный вход 2', 'Дискретный вход 2')], max_length=250)),
                ('alarm', models.BooleanField()),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.filial')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureSensorVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('Датчик', 'Датчик'), ('Термощуп', 'Термощуп')], max_length=250)),
                ('unit', models.CharField(max_length=250)),
                ('HH', models.FloatField()),
                ('LL', models.FloatField()),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.filial')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.sensor')),
            ],
        ),
    ]
