# Generated by Django 5.0.3 on 2024-09-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='type',
        ),
        migrations.AddField(
            model_name='journal',
            name='variable_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
