# Generated by Django 5.1.1 on 2024-09-25 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_remove_journal_type_journal_variable_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
